# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to Blend'it homepages
<!-- email: your-email@domain.com -->
description: > # this means to ignore newlines until "baseurl:"
	This is the website of Blend'it, a project launched by 9 Master
	students at the ENS Lyon. Our goal is to improve the generation of
	crowds and environments within Blender.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blendit.github.io" # the base hostname & protocol for your site
github_username:  blendit

# Build settings
markdown: kramdown
